function drawProtectedTarget(ax_main, ax_3d, target)
    % Vẽ mục tiêu bảo vệ với vòng tròn cảnh báo
    pos = target.pos;
    
    % Vòng tròn bảo vệ
    theta = linspace(0, 2*pi, 100);
    radius = 5000;
    x_circle = pos(1) + radius * cos(theta);
    y_circle = pos(2) + radius * sin(theta);
    
    % 2D
    plot(ax_main, pos(1), pos(2), 'd', ...
         'MarkerSize', 10, ...
         'MarkerFaceColor', [0.3, 1, 0.9], ...
         'MarkerEdgeColor', [1, 1, 1], ...
         'LineWidth', 1);
    
    % Đường vòng cảnh báo (dùng RGB nhân hệ số, tránh RGBA)
    plot(ax_main, x_circle, y_circle, ':', ...
         'LineWidth', 0.8, ...
         'Color', [0.3, 1, 0.9] * 0.5);
    
    text(ax_main, pos(1)+1200, pos(2)+1200, target.name, ...
         'Color', [0.3, 1, 0.9], ...
         'FontSize', 9, ...
         'BackgroundColor', [0, 0, 0], ...
         'Margin', 2);
    
    % 3D
    plot3(ax_3d, pos(1), pos(2), pos(3), 'd', ...
          'MarkerSize', 9, ...
          'MarkerFaceColor', [0.3, 1, 0.9], ...
          'MarkerEdgeColor', [1, 1, 1], ...
          'LineWidth', 0.8);
end