function drawSCH(ax_main, ax_3d, SCH)
    % Vẽ Sở Chỉ Huy
    pos = SCH.pos;
    
    % 2D
    plot(ax_main, pos(1), pos(2), 'p', ...
         'MarkerSize', 16, ...
         'MarkerFaceColor', [0.2, 0.9, 1], ...
         'MarkerEdgeColor', [1, 1, 1], ...
         'LineWidth', 1.2);
    
    text(ax_main, pos(1)+1200, pos(2)+1200, 'SCH', ...
         'Color', [0.2, 0.9, 1], ...
         'FontWeight', 'bold', ...
         'FontSize', 11, ...
         'BackgroundColor', [0, 0, 0, 0.5], ...
         'EdgeColor', [0.2, 0.9, 1], ...
         'LineWidth', 0.8, ...
         'Margin', 2);
    
    % 3D
    plot3(ax_3d, pos(1), pos(2), pos(3), 'p', ...
          'MarkerSize', 14, ...
          'MarkerFaceColor', [0.2, 0.9, 1], ...
          'MarkerEdgeColor', [1, 1, 1], ...
          'LineWidth', 1);
end