function drawFireUnit(ax_main, ax_3d, unit, color)
    % Vẽ đơn vị hỏa lực với vòng tầm bắn
    pos = unit.pos;
    theta = linspace(0, 2*pi, 360);
    
    % 2D
    plot(ax_main, pos(1), pos(2), 'o', ...
         'MarkerSize', 9, ...
         'MarkerFaceColor', color, ...
         'MarkerEdgeColor', [1, 1, 1], ...
         'LineWidth', 1);
    
    % Vòng tầm bắn tối đa
    x_max = pos(1) + unit.range_max * cos(theta);
    y_max = pos(2) + unit.range_max * sin(theta);
    plot(ax_main, x_max, y_max, '--', ...
         'LineWidth', 0.8, ...
         'Color', [color, 0.4]);
    
    % Vòng tầm bắn tối thiểu
    x_min = pos(1) + unit.range_min * cos(theta);
    y_min = pos(2) + unit.range_min * sin(theta);
    plot(ax_main, x_min, y_min, ':', ...
         'LineWidth', 0.6, ...
         'Color', [color, 0.5]);
    
    text(ax_main, pos(1)+1200, pos(2)+1200, unit.name, ...
         'Color', [1, 1, 1], ...
         'FontSize', 9, ...
         'BackgroundColor', [color, 0.7], ...
         'EdgeColor', [1, 1, 1], ...
         'LineWidth', 0.6, ...
         'Margin', 2);
    
    % 3D
    plot3(ax_3d, pos(1), pos(2), pos(3), 'o', ...
          'MarkerSize', 8, ...
          'MarkerFaceColor', color, ...
          'MarkerEdgeColor', [1, 1, 1], ...
          'LineWidth', 0.8);
end