function [h_marker, h_label, h_traj] = drawTarget2D(sim_state, target_idx)
    % Vẽ mục tiêu trên màn hình 2D
    
    target = sim_state.targets(target_idx);
    pos = target.pos;
    
    % Tính điểm Bj
    Bj = calculateThreatLevel(target, sim_state.SCH.pos(1:2), sim_state.targets_protect, sim_state.fire_units);
    
    % Lấy màu
    color = getThreatColor(Bj);
    bg_color = getThreatBackgroundColor(Bj);
    
    % Vẽ marker
    h_marker = plot(sim_state.ax_main, pos(1), pos(2), target.marker, ...
        'MarkerSize', 11, ...
        'MarkerFaceColor', color, ...
        'MarkerEdgeColor', [1, 1, 1], ...
        'LineWidth', 1.3);
    
    % Tạo label
    dist_to_sch = norm(pos(1:2) - sim_state.SCH.pos(1:2)) / 1000;
    
    if target.priority_from_command
        label_text = sprintf('⚡ %s\n%s\nBj=%.2f ★\nH=%dk | D=%.1fkm', ...
            target.name, target.type, Bj, ...
            round(target.H/1000), dist_to_sch);
    else
        label_text = sprintf('%s\n%s\nBj=%.2f ★\nH=%dk | D=%.1fkm', ...
            target.name, target.type, Bj, ...
            round(target.H/1000), dist_to_sch);
    end
    
    h_label = text(sim_state.ax_main, pos(1)+2000, pos(2)+2000, label_text, ...
        'Color', [1, 1, 1], ...
        'FontWeight', 'bold', ...
        'FontSize', 7.5, ...
        'FontName', 'Arial', ...
        'BackgroundColor', bg_color, ...
        'EdgeColor', color, ...
        'LineWidth', 1, ...
        'Margin', 2.5);
    
    % Vẽ quỹ đạo
    traj = sim_state.trajectories{target_idx};
    if size(traj, 1) > 1
        h_traj = plot(sim_state.ax_main, traj(:,1), traj(:,2), '-', ...
            'Color', [color, 0.6], ...
            'LineWidth', 1.8);
    else
        h_traj = gobjects(1);
    end
end