function [target_tables, buttons, checkboxes] = createControlPanel(fig, targets)
    % Tạo panel thông tin và điều khiển
    
    % Panel thông tin mục tiêu
    info_panel = uipanel(fig, ...
        'Title', 'THÔNG TIN MỤC TIÊU DỰ ĐOÁN', ...
        'Position', [0.03, 0.01, 0.60, 0.32], ...
        'BackgroundColor', [0.08, 0.08, 0.12], ...
        'ForegroundColor', [0.95, 0.95, 1], ...
        'FontSize', 11, ...
        'FontWeight', 'bold');
    
    % Tạo bảng cho từng mục tiêu — chia đều theo kích thước thực của panel
    % (getpixelposition tránh phụ thuộc vào hằng số cứng không khớp panel)
    n_targets = length(targets);
    panel_px = getpixelposition(info_panel);
    margin = 10;
    table_width = (panel_px(3) - margin * (n_targets + 1)) / n_targets;
    table_height = panel_px(4) - 20;

    target_tables = cell(n_targets, 1);
    for i = 1:n_targets
        x_pos = margin + (i-1) * (table_width + margin);
        target_tables{i} = uitable(info_panel, ...
            'Position', [x_pos, 10, table_width, table_height], ...
            'ColumnName', {'Thông số', 'Giá trị'}, ...
            'ColumnWidth', {round(table_width*0.38), round(table_width*0.56)}, ...
            'RowName', [], ...
            'FontSize', 9, ...
            'ForegroundColor', [0.9, 0.9, 0.9]);
    end
    
    % Panel điều khiển
    control_panel = uipanel(fig, ...
        'Title', 'ĐIỀU KHIỂN', ...
        'Position', [0.62, 0.01, 0.35, 0.32], ...
        'BackgroundColor', [0.08, 0.08, 0.12], ...
        'ForegroundColor', [0.95, 0.95, 1], ...
        'FontSize', 11, ...
        'FontWeight', 'bold');
    
    % Nút điều khiển
    buttons = struct();
    
    buttons.start = uicontrol(control_panel, ...
        'Style', 'pushbutton', ...
        'String', '▶ BẮT ĐẦU', ...
        'Position', [20, 180, 120, 40], ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.2, 0.6, 0.3], ...
        'ForegroundColor', [1, 1, 1], ...
        'Callback', @(src, evt) startSimulation(src));
    
    buttons.pause = uicontrol(control_panel, ...
        'Style', 'pushbutton', ...
        'String', '⏸ TẠM DỪNG', ...
        'Position', [160, 180, 120, 40], ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.8, 0.6, 0.1], ...
        'ForegroundColor', [1, 1, 1], ...
        'Enable', 'off', ...
        'Callback', @(src, evt) pauseSimulation(src));
    
    buttons.reset = uicontrol(control_panel, ...
        'Style', 'pushbutton', ...
        'String', '🔄 RESET', ...
        'Position', [300, 180, 120, 40], ...
        'FontSize', 11, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.6, 0.2, 0.2], ...
        'ForegroundColor', [1, 1, 1], ...
        'Callback', @(src, evt) resetSimulation(src));
    
    % Nhãn checkbox
    uicontrol(control_panel, ...
        'Style', 'text', ...
        'String', 'CHỈ THỊ TỪ CẤP TRÊN:', ...
        'Position', [20, 140, 400, 25], ...
        'FontSize', 10, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.08, 0.08, 0.12], ...
        'ForegroundColor', [1, 0.8, 0.2], ...
        'HorizontalAlignment', 'left');
    
    % Checkbox cho từng mục tiêu
    checkboxes = cell(length(targets), 1);
    for i = 1:length(targets)
        y_pos = 110 - (i-1) * 30;
        checkboxes{i} = uicontrol(control_panel, ...
            'Style', 'checkbox', ...
            'String', sprintf('%s - %s', targets(i).name, targets(i).type), ...
            'Position', [30, y_pos, 380, 25], ...
            'FontSize', 9, ...
            'BackgroundColor', [0.08, 0.08, 0.12], ...
            'ForegroundColor', [0.9, 0.9, 0.9], ...
            'Callback', @(src, evt) togglePriority(src, i));
    end
end