function tgt = createTarget(id, name, type, speed_cruise, RCS, maneuver, ...
                            task, jam_type, group_size, waypoints, color, marker)
    %% TẠO CẤU TRÚC MỤC TIÊU CHUẨN VỚI ĐỘNG LỰC HỌC
    % waypoints: Ma trận Nx3 [x, y, z]
    
    % Xác định các tham số theo loại mục tiêu (dựa vào Bảng 2)
    if contains(type, 'B52') || contains(type, 'chiến lược') || contains(type, 'MB ném bom')
        % ═══ B52 / MÁY BAY NÉM BOM CHIẾN LƯỢC ═══
        RCS_min = 5;
        RCS_max = 20;
        speed_min = 250;
        speed_max = 700;
        accel_max = 1.0;       % m/s² (rất thấp)
        n_max = 3.0;           % 2-4 G (trung bình 3G)
        min_turn_radius = 8000; % Bán kính quẹo tối thiểu 8km (rất lớn)
        
    elseif contains(type, 'Tiêm kích ném bom') || contains(type, 'ném bom')
        % ═══ TIÊM KÍCH NÉM BOM ═══
        RCS_min = 2;
        RCS_max = 5;
        speed_min = 320;
        speed_max = 750;
        accel_max = 3.0;       % m/s²
        n_max = 5.5;           % 5-6 G (trung bình 5.5G)
        min_turn_radius = 3000; % 3km
        
    elseif contains(type, 'Tiêm kích') || contains(type, 'chiến thuật')
        % ═══ TIÊM KÍCH CHIẾN THUẬT ═══
        RCS_min = 1;
        RCS_max = 5;
        speed_min = 350;
        speed_max = 750;
        accel_max = 5.0;       % m/s² (cao)
        n_max = 7.5;           % 6.5-9 G (trung bình 7.5G)
        min_turn_radius = 2000; % 2km (cơ động cao)
        
    elseif contains(type, 'Tên lửa') || contains(type, 'hành trình')
        % ═══ TÊN LỬA HÀNH TRÌNH ═══
        RCS_min = 0.01;
        RCS_max = 2.5;
        speed_min = 250;
        speed_max = 1200;
        accel_max = 2.0;       % m/s²
        n_max = 1.5;           % 1-2 G (rất thấp, bay thẳng)
        min_turn_radius = 5000; % 5km (quẹo rất thoải)
        
    else
        % Mặc định
        RCS_min = RCS * 0.5;
        RCS_max = RCS * 2;
        speed_min = speed_cruise * 0.7;
        speed_max = speed_cruise * 1.3;
        accel_max = 2.0;
        n_max = maneuver;
        min_turn_radius = 4000;
    end
    
    tgt = struct( ...
        'id', id, ...
        'name', name, ...
        'type', type, ...
        'pos', waypoints(1, :), ...
        'vel', [0, 0, 0], ...
        'speed', speed_cruise * 0.8, ...
        'speed_min', speed_min, ...
        'speed_max', speed_max, ...
        'speed_cruise', speed_cruise, ...
        'accel_max', accel_max, ...
        'current_accel', 0, ...
        'maneuver_ability', n_max, ...
        'min_turn_radius', min_turn_radius, ...  % ← THÊM MỚI
        'waypoints', waypoints, ...
        'smooth_path', [], ...
        'path_index', 1, ...
        'RCS', RCS, ...
        'RCS_min', RCS_min, ...
        'RCS_max', RCS_max, ...
        'RCS_real', RCS, ...
        'RCS_eff', RCS, ...
        'distance_to_DVHL', inf, ...
        'jam_type', jam_type, ...
        'task', task, ...
        'group_size', group_size, ...
        'priority_from_command', false, ...
        'status', 'Đang bay', ...
        'color', color, ...
        'marker', marker, ...
        'trajectory_history', [] ...
    );
end