function fu = createFireUnit(name, pos)
    % Tạo cấu trúc đơn vị hỏa lực chuẩn
    fu = struct( ...
        'name', name, ...
        'pos', pos, ...
        'range_max', 35000, ...
        'range_min', 3500, ...
        'H_max', 25000, ...
        'H_min', 100, ...
        'status', 'Sẵn sàng' ...
    );
end