function tgt = createTarget(id, name, type, speed, H, RCS, maneuver, ...
                            task, jam_type, group_size, waypoints, color, marker)
    % Tạo cấu trúc mục tiêu chuẩn
    tgt = struct( ...
        'id', id, ...
        'name', name, ...
        'type', type, ...
        'speed', speed, ...
        'H', H, ...
        'RCS', RCS, ...
        'maneuver_ability', maneuver, ...
        'task', task, ...
        'jam_type', jam_type, ...
        'group_size', group_size, ...
        'priority_from_command', false, ...
        'waypoints', waypoints, ...
        'pos', [waypoints(1,:), H], ...
        'vel', [0, 0, 0], ...
        'color', color, ...
        'marker', marker, ...
        'status', 'Đang bay', ...
        'smooth_path', [], ...
        'path_index', 1 ...
    );
end