function tgt = createTarget(id, name, type, speed, H, RCS, maneuver, ...
                            task, jam_type, group_size, waypoints, color, marker)
    %% TẠO CẤU TRÚC MỤC TIÊU CHUẨN   
    tgt = struct( ...
        ...         % NHÓM 1: THÔNG TIN ĐỊNH DANH
        'id', id, ...
        'name', name, ...
        'type', type, ...
        ...        % NHÓM 2: TỌA ĐỘ VÀ CÁC THAM SỐ CHUYỂN ĐỘNG
        'pos', [waypoints(1,:), H], ...
        'vel', [0, 0, 0], ...
        'speed', speed, ...
        'H', H, ...
        'waypoints', waypoints, ...
        'smooth_path', [], ...
        'path_index', 1, ...
        ...        % NHÓM 3: CÁC ĐẶC TRƯNG VÀ DẤU HIỆU CỦA MỤC TIÊU
        'RCS', RCS, ...
        'maneuver_ability', maneuver, ...
        'jam_type', jam_type, ...
        'task', task, ...
        'group_size', group_size, ...
        ...        % NHÓM 4: CÁC THAM SỐ VỊ TRÍ KHÔNG GIAN, THỜI GIAN VÀ SO VỚI VÙNG PHÒNG THỦ
        'priority_from_command', false, ...
        'status', 'Đang bay', ...
        ...        % NHÓM 5: KÝ HIỆU VẼ (VISUALIZATION)
        'color', color, ...
        'marker', marker ...
    );
end