function gt_window = createGroundTruthWindow(targets)
    %% TẠO CỬA SỔ HIỂN THỊ THÔNG TIN GROUND TRUTH (ENEMY)
    % Hiển thị thông tin thực của mục tiêu (không có sai số)
    
    % Tạo figure
    gt_window = struct();
    gt_window.fig = figure('Name', 'Ground Truth - Thông tin thực mục tiêu (Enemy)', ...
        'NumberTitle', 'off', ...
        'Position', [100, 100, 1200, 600], ...
        'MenuBar', 'none', ...
        'Toolbar', 'none', ...
        'Color', [0.94, 0.94, 0.94]);
    
    % Tạo panel chứa các bảng
    main_panel = uipanel(gt_window.fig, ...
        'Position', [0.02, 0.02, 0.96, 0.96], ...
        'Title', '📊 GROUND TRUTH - THÔNG TIN THỰC CỦA MỤC TIÊU', ...
        'FontSize', 12, ...
        'FontWeight', 'bold', ...
        'BackgroundColor', [0.94, 0.94, 0.94]);
    
    % Tính số cột và hàng
    n_targets = length(targets);
    n_cols = min(2, n_targets);  % Tối đa 2 cột
    n_rows = ceil(n_targets / n_cols);
    
    % Tạo bảng cho từng mục tiêu
    gt_window.tables = cell(n_targets, 1);
    
    for i = 1:n_targets
        % Tính vị trí
        col = mod(i-1, n_cols) + 1;
        row = ceil(i / n_cols);
        
        x = 0.02 + (col-1) * (0.96 / n_cols);
        y = 0.98 - row * (0.96 / n_rows);
        w = 0.96 / n_cols - 0.02;
        h = 0.96 / n_rows - 0.02;
        
        % Tạo panel cho mục tiêu
        target_panel = uipanel(main_panel, ...
            'Position', [x, y, w, h], ...
            'Title', sprintf('🎯 %s (ID: %d)', targets(i).name, targets(i).id), ...
            'FontSize', 10, ...
            'FontWeight', 'bold', ...
            'BackgroundColor', [1, 1, 1]);
        
        % Tạo bảng
        gt_window.tables{i} = uitable(target_panel, ...
            'Position', [10, 10, w*gt_window.fig.Position(3)-20, h*gt_window.fig.Position(4)-50], ...
            'Units', 'normalized', ...
            'Position', [0.02, 0.02, 0.96, 0.96], ...
            'ColumnName', {'Tham số', 'Giá trị THỰC'}, ...
            'ColumnWidth', {180, 200}, ...
            'RowName', [], ...
            'FontSize', 9);
    end
    
    fprintf('✓ Đã tạo cửa sổ Ground Truth\n');
end